[package]
name = "workspace"
version = "0.1.0"
edition = "2024"

[dependencies]
collection = { path = "../collection" }
gpui.workspace = true
gpui-component.workspace = true
gpui_platform.workspace = true
keybindings_service = { path = "../keybindings_service" }
reqwest_client.workspace = true

[dev-dependencies]
gpui = { git = "https://github.com/zed-industries/zed", features = ["test-support"] }
