[package]
name = "workspace"
version = "0.1.0"
edition = "2024"

[dependencies]
collection = { path = "../collection" }
gpui-kit = { workspace = true, features = ["component"] }
keybindings_service = { path = "../keybindings_service" }
updater = { path = "../updater" }

[dev-dependencies]
gpui-kit = { workspace = true, features = ["test-support"] }
serde_json = "1"
smol = "2"
